# Generated by Django 6.0.2 on 2026-07-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
